language: rust

rust:
  - nightly

dist: xenial

env:
  - TARGET=x86_64-unknown-linux-gnu BUILD_MODE=reprotest

before_install:
  - sudo ci/dependencies.sh "$TARGET"

install:
  - rustup install "$TRAVIS_RUST_VERSION-$TARGET"
  - rustup target add "$TARGET" || true

script:
  - ci/build.sh
  - ci/test.sh
