language: rust
dist: xenial

env:
  - TARGET=x86_64-unknown-linux-gnu CC=gcc
  - TARGET=i686-unknown-linux-gnu CC=gcc
  - TARGET=aarch64-unknown-linux-gnu CC=aarch64-linux-gnu-gcc
  - TARGET=arm-unknown-linux-gnueabihf CC=arm-linux-gnueabihf-gcc

before_install:
  - sudo ci/dependencies.sh "$TARGET"

install:
  - rustup install "$TRAVIS_RUST_VERSION-$TARGET"
  - rustup target add "$TARGET" || true

script:
  - cargo build --verbose --target "$TARGET"
  - cargo test --verbose --target "$TARGET"

rust:
  - nightly
