language: rust
dist: xenial

env:
  - TARGET=x86_64-unknown-linux-gnu CC=gcc TARGET_CC=gcc
  - TARGET=i686-unknown-linux-gnu CC=gcc TARGET_CC=gcc
  - TARGET=aarch64-unknown-linux-gnu CC=gcc TARGET_CC=aarch64-linux-gnu-gcc
  - TARGET=arm-unknown-linux-gnueabihf CC=gcc TARGET_CC=arm-linux-gnueabihf-gcc

before_install:
  - sudo ci/dependencies.sh "$TARGET"

install:
  - rustup install "$TRAVIS_RUST_VERSION-$TARGET"
  - rustup target add "$TARGET" || true

script:
  - cargo build -vv --target "$TARGET"
  - cargo test -vv --target "$TARGET"

rust:
  - nightly
