language: rust

rust:
  - nightly

dist: xenial

env:
  - TARGET=x86_64-unknown-linux-gnu
  - TARGET=x86_64-unknown-linux-gnu BUILD_MODE=reprotest
  - TARGET=i686-unknown-linux-gnu TARGET_CC=gcc
  - TARGET=aarch64-unknown-linux-gnu TARGET_CC=aarch64-linux-gnu-gcc QEMU_LD_PREFIX=/usr/aarch64-linux-gnu
  - TARGET=arm-unknown-linux-gnueabihf TARGET_CC=arm-linux-gnueabihf-gcc QEMU_LD_PREFIX=/usr/arm-linux-gnueabihf
  - TARGET=armv7-unknown-linux-gnueabihf TARGET_CC=arm-linux-gnueabihf-gcc QEMU_LD_PREFIX=/usr/arm-linux-gnueabihf

before_install:
  - sudo ci/dependencies.sh "$TARGET"

install:
  - rustup install "$TRAVIS_RUST_VERSION-$TARGET"
  - rustup target add "$TARGET" || true

script:
  - ci/build.sh
  - ci/test.sh
