FROM debian:testing

RUN apt-get update -qq && \
    DEBIAN_FRONTEND=noninteractive apt-get upgrade -qq -y && \
    DEBIAN_FRONTEND=noninteractive apt-get install -qq -y \
            build-essential \
            curl \
            diffoscope

ENV PYTHONIOENCODING=utf-8

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly && \
    cp ~/.cargo/bin/rustup ~/.cargo/bin/cargo ~/.cargo/bin/rustc /usr/bin/

WORKDIR /rocket-tls/

COPY . .
